### ISSUE TITLE
not build with qt 5.5.1

### ISSUE THREAD

**Issue by sabrabano0** [devbean/QtCipherSqlitePlugin#35]
as your wiki i open the project in qt and build it but this is the bugs:

D:\Qt\Apps\QtCipherSqlitePlugin-master\sqlitecipher\sqlite3\fastpbkdf2.c:259: error: expected ';', ',' or ')' before 'ctx'
 static inline void sha1_extract(sha1_ctx *restrict ctx, uint8_t *restrict out)
                                                    ^
D:\Qt\Apps\QtCipherSqlitePlugin-master\sqlitecipher\sqlite3\fastpbkdf2.c:268: error: expected ';', ',' or ')' before 'out'
 static inline void sha1_cpy(sha1_ctx *restrict out, const sha1_ctx *restrict in)
                                                ^
D:\Qt\Apps\QtCipherSqlitePlugin-master\sqlitecipher\sqlite3\fastpbkdf2.c:277: error: expected ';', ',' or ')' before 'out'
 static inline void sha1_xor(sha1_ctx *restrict out, const sha1_ctx *restrict in)
                                                ^

**Comment by mimcimm** [comment]
For me too. I have 5.2.1 in my company but I have the same problem.
I tried oın 5.10 and its working fine
